/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	_ "github.com/go-sql-driver/mysql"
	sw "github.com/godpeny/goserv/cmd/go-server/go"
	model "github.com/godpeny/goserv/init/model"
)

func main() {
	// set db
	client, err := model.InitModel()
	if err != nil {
		log.Fatalf("failed init Model : %v", err)
	}
	defer client.Close()

	log.Printf("Server started")

	router := sw.NewRouter()

	log.Fatal(router.Run(":8080"))
}
