/*
 * goserv
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"

	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	_ "github.com/go-sql-driver/mysql"
	sw "github.com/godpeny/goserv/cmd/go-server/go"
	model "github.com/godpeny/goserv/init/model"
)

func main() {
	// set db
	client, err := model.InitModel()
	if err != nil {
		log.Fatalf("failed init Model : %v", err)
	}
	defer client.Close()

	log.Printf("Server started")
	router := sw.NewRouter()

	log.Fatal(http.ListenAndServe(":8080", router))
}
