openapi: 3.0.0
info:
  title: sample
  license:
    name: MIT
  version: 1.0.0
servers:
- url: /
paths:
  /api/ping:
    post:
      tags:
      - CLIENT
      summary: Create Request
      operationId: Create API Request
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Request'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Response'
        "400":
          description: Bad request
        "404":
          description: Not found
components:
  schemas:
    Request:
      required:
      - name
      - type
      type: object
      properties:
        type:
          type: string
        name:
          type: string
    Response:
      required:
      - etc
      - name
      - num
      - target
      - type
      type: object
      properties:
        num:
          type: string
        target:
          type: string
        type:
          type: string
        name:
          type: string
        etc:
          type: string
      example:
        etc: etc
        num: num
        name: name
        type: type
        target: target
