/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

// WARNING!
// Change this to a fully-qualified import path
// once you place this file into your project.
// For example,
//
//    sw "github.com/myname/myrepo/go"
//

func main() {
	// goserv-api excutable is in 'goserv/cmd/goserv' !!
	// use path above to excute goserv-api instead of this path :)
}
