openapi: 3.0.0
info:
  title: goserv
  license:
    name: MIT
  version: 0.0.1
servers:
- url: /
paths:
  /ping:
    get:
      tags:
      - SERVER
      summary: check whether server is on
      operationId: "null"
      responses:
        "200":
          description: goserv server health check
          content:
            text/plain:
              schema:
                type: string
                x-content-type: text/plain
        "400":
          description: Bad request
        "404":
          description: Not found
components: {}
