/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// HealthCheck - server health check
func HealthCheck(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
