/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type ApiResponse struct {

	Code int64 `json:"code,omitempty"`

	Id int64 `json:"id,omitempty"`

	Message string `json:"message,omitempty"`

	Type string `json:"type,omitempty"`
}
