/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// V1User - A User Schema
type V1User struct {

	Age int64 `json:"age"`

	Name string `json:"name"`
}
