/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"

	"github.com/gin-gonic/gin"

	ent "github.com/godpeny/goserv/ent"
	db "github.com/godpeny/goserv/internal/goserv-db"
)

// CreateUser - create user
func CreateUser(c *gin.Context) {
	req := &ent.User{}

	if err := c.BindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db.RunMQ_User("CREATE", *req, c)
	res := <-db.APIc

	c.JSON(http.StatusOK, res)
}

// DeleteUser - Delete user
func DeleteUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetUserByName - Get user by user name
func GetUserByName(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ListUser - list users
func ListUser(c *gin.Context) {
	req := &ent.User{}

	if err := c.BindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	db.RunMQ_User("READ", *req, c)
	res := <-db.APIc

	c.JSON(http.StatusOK, res)
}

// UpdateUser - Updated user
func UpdateUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
