/*
 * Goserver in Open API
 *
 * server template in GO.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

type User struct {

	Age int64 `json:"age,omitempty"`

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`
}
