// Code generated by entc, DO NOT EDIT.

package apiresponse

const (
	// Label holds the string label denoting the apiresponse type in the database.
	Label = "api_response"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCode holds the string denoting the code field in the database.
	FieldCode = "code"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"

	// Table holds the table name of the apiresponse in the database.
	Table = "api_responses"
)

// Columns holds all SQL columns for apiresponse fields.
var Columns = []string{
	FieldID,
	FieldCode,
	FieldType,
	FieldMessage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// CodeValidator is a validator for the "code" field. It is called by the builders before save.
	CodeValidator func(int) error
	// DefaultType holds the default value on creation for the type field.
	DefaultType string
	// DefaultMessage holds the default value on creation for the message field.
	DefaultMessage string
)
