/*
 * sample
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Response struct {
	Num string `json:"num"`
	Target string `json:"target"`
	Type_ string `json:"type"`
	Name string `json:"name"`
	Etc string `json:"etc"`
}
