# TODO : seperate components and paths
components:
  schemas:
    v1_user:
      type: object
      required:
        - name
        - age
      properties:
        name: 
          type: string
        age:
          format: int64
          type: integer
info:
    license:
      name: MIT
    title: goserv
    version: 0.0.1
openapi: 3.0.0
paths:
    /ping:
      get:
        operationId: healthCheck
        responses:
          200:
            description: "goserv server health check"
            content:
              text/plain:
                schema:
                  type: string
                  response: pong
          400:
            description: "Bad request"
          404:
            description: "Not found"
        summary: check whether server is on
        tags:
          - "SERVER"
    /api/v1/user:
      post:
        operationId: createUser
        requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/v1_user'
        required: true 
        responses:
          200:
            description: "create user"
            content:
              text/plain:
                schema:
                  type: string
                  response: pong
          400:
            description: "Bad request"
          404:
            description: "Not found"
        summary: create user
        tags:
          - "user"