// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
